version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: olp
      POSTGRES_USER: olpuser
      POSTGRES_PASSWORD: olppass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=olp
      - DATABASE_USER=olpuser
      - DATABASE_PASSWORD=olppass
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: ["npm", "start"]
    depends_on:
      - backend
volumes:
  postgres_data:
